
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: root
  redis:
    host: 59.110.233.202
    connect-timeout: 3000
    lettuce:
      shutdown-timeout:
    port: 7001
#    host:

mybatis:
  type-aliases-package: com.example.redis
  mapper-locations: classpath:com/example/redis/mapper/*.xml